name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - test_gh_actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add remote server to known hosts
        run: |
          ssh-keyscan -p ${{ secrets.PORT}} -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts
        shell: bash

      - name: SSH to remote server
        run: ssh -v -p ${{ secrets.PORT}} ec2-user@${{ secrets.HOST_IP }} "whoami"
    # Test running a seperate script
      - name: Run a script
        run: ./test.sh
        env:
            PORT: ${{ secrets.PORT }}
            HOST_IP: ${{ secrets.HOST_IP }}